### ISSUE TITLE
2019/07/24 CSSカスタムプロパティを使っているフレームワークでIE対応をする

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/learned#8]
[Material Components for the web](https://github.com/material-components/material-components-web)のようにCSSカスタムプロパティを使用しているフレームワークがある。
[IEはCSSカスタムプロパティ非対応](https://caniuse.com/#feat=css-variables)なので、現状では対策が必要。

1. ponyfillの[css-vars-ponyfill](https://github.com/jhildenbiddle/css-vars-ponyfill)を使う
2. postcss-custom-propertiesで静的CSSに変換する

## ponyfillの[css-vars-ponyfill](https://github.com/jhildenbiddle/css-vars-ponyfill)を使う
`:root`以外でCSSカスタムプロパティを使っていない場合に使える。JSで動的に変換できる点で優位。

[ドキュメント](https://jhildenbiddle.github.io/css-vars-ponyfill/#/)にあるようにインストールする。

```
npm install css-vars-ponyfill
```

インポートして実行する。

```js
import cssVars from 'css-vars-ponyfill';
cssVars();
```

`head`タグ内にテスト用の変数を追加する。

```html
  <style>
    :root {
      --color: black;
    }
  </style>
</head>
```

`body`内に`div`を追加して反映を確認する。

```html
<body>
  <div>div</div>
```

CSSを追加する。`:root`以外での反映を確認するため、`div`に`--color: red;`を追加した。

```css
:root {
  --a: var(--b); /* Chained */
  --b: var(--c);
  --c: 10px;
}

div {
  --color: red;

  color: var(--color); /* from <style> */
  margin: var(--unknown, 20px); /* Fallback */
  padding: calc(2 * var(--a)); /* Nested */
}
```

IEのみ`head`タグ内に以下のように`style`タグでインライン出力された。

```html
<style data-cssvars="out" data-cssvars-job="1" data-cssvars-group="1">
</style>
```

```css
  div {
    color: black;
    margin: 20px;
    padding: calc(2 * 10px);
  }
```

`div {}`内の`--color: red;`は変換されなかった。

## postcss-custom-propertiesで静的CSSに変換する
Laravel Mixだと以下のように設定する。`preserve: false`にすると、`var()`は削除される。
JSで動的に追加されたカスタムプロパティは非対応ブラウザで反映されない。

```js
mix
  .js('src/assets/js/app.js', 'dist/assets/js/')
  .sass('src/assets/css/app.scss', 'dist/assets/css/')
  .options({
    processCssUrls: false,
    autoprefixer: {
      options: {
        grid: true,
      },
    },
    postCss: [
      require('postcss-custom-properties')({
        preserve: false
      })
    ],
  });
```
